
name: CI
on: 
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  call-test:
    uses: Dasperless/cicd-templates/.github/workflows/test.yml@main
    with:
      environment: dev

